### ISSUE TITLE
Withdrawing Pokemon messes up the Pokedex

### ISSUE THREAD

**Issue by GengarFan95** [git-afsantos/crystal50#11]
When I withdraw a Pokemon from the PC, weird things happen to my Pokedex. Random Pokemon get registered as caught, or Pokemon that I have caught get unregistered

**Comment by oatspear** [comment]
@GengarFan95 This is not happening with my emulator, so let's try to pinpoint the issue.

What version of the game are you using? The most recent?

Did you build it from source, or did you get a patch file?

If it was a patch file, in which format was it? IPS, or the most recent BPS?

**Comment by GengarFan95** [comment]
I've been using an IPS patch file for version 1.1. The emulator I've used was VBA

**Comment by oatspear** [comment]
@GengarFan95 Hm, I see. VBA has been known in the community to cause all sorts of issues.

First, I would recommend building the ROM from the new BPS or UPS file (it's in the Releases of this repository).

These are better than IPS, because they will give you an error if we are not using the same base ROM.

If that still doesn't work, then my second recommendation would be to try with another emulator that is accurate with Game Boy hardware, like MGBA, SameBoy, BGB, and others.

It's an inconvenience, I know, but I am still unsure whether this will ever work perfectly with VBA.

**Comment by GengarFan95** [comment]
I think I'm gonna wait for the Bug Bite/Pluck bug to be fixed first before trying to build this from source, if you don't mind
